// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: tracelet_location.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location Report
// Sent from Tracelet to the consuming system (consumer) via TCP port
// - Tracelet is TCP client
// - Consumer is TCP server
//
// Format of a TCP message:
// - Byte 0: 0xFE
// - Byte 1: 0xED
// - Byte 2..5: Length of marshalled protobuf data (Byte 2=LSB)
// - Byte 6..n: Marshalled Protobuf Data (LocationReport Message)
type LocationReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// timestamp when location data was received from easylocate system
	// resolution of tracelet: ms
	ReceiveTs *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=receive_ts,json=receiveTs,proto3" json:"receive_ts,omitempty"`
	// tracelet ID as provisioned in tracelet. Could be a vehicle ID
	TraceletId string `protobuf:"bytes,2,opt,name=tracelet_id,json=traceletId,proto3" json:"tracelet_id,omitempty"`
	// location of tracelet in space
	// Units: [m], can be negative. Resolution 0.1m
	X float64 `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,5,opt,name=z,proto3" json:"z,omitempty"`
	// Site ID
	// a 16 bit unsigned value
	SiteId uint32 `protobuf:"varint,6,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// Location signature
	// can be used to validate the received location
	LocationSignature uint64 `protobuf:"fixed64,7,opt,name=location_signature,json=locationSignature,proto3" json:"location_signature,omitempty"`
	// Covariance. See Easylocate Specification for details
	CovXx float64 `protobuf:"fixed64,8,opt,name=cov_xx,json=covXx,proto3" json:"cov_xx,omitempty"`
	CovXy float64 `protobuf:"fixed64,9,opt,name=cov_xy,json=covXy,proto3" json:"cov_xy,omitempty"`
	CovYy float64 `protobuf:"fixed64,10,opt,name=cov_yy,json=covYy,proto3" json:"cov_yy,omitempty"`
}

func (x *LocationReport) Reset() {
	*x = LocationReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracelet_location_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationReport) ProtoMessage() {}

func (x *LocationReport) ProtoReflect() protoreflect.Message {
	mi := &file_tracelet_location_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationReport.ProtoReflect.Descriptor instead.
func (*LocationReport) Descriptor() ([]byte, []int) {
	return file_tracelet_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationReport) GetReceiveTs() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceiveTs
	}
	return nil
}

func (x *LocationReport) GetTraceletId() string {
	if x != nil {
		return x.TraceletId
	}
	return ""
}

func (x *LocationReport) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LocationReport) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LocationReport) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *LocationReport) GetSiteId() uint32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *LocationReport) GetLocationSignature() uint64 {
	if x != nil {
		return x.LocationSignature
	}
	return 0
}

func (x *LocationReport) GetCovXx() float64 {
	if x != nil {
		return x.CovXx
	}
	return 0
}

func (x *LocationReport) GetCovXy() float64 {
	if x != nil {
		return x.CovXy
	}
	return 0
}

func (x *LocationReport) GetCovYy() float64 {
	if x != nil {
		return x.CovYy
	}
	return 0
}

var File_tracelet_location_proto protoreflect.FileDescriptor

var file_tracelet_location_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6c, 0x65, 0x74, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x61, 0x73, 0x79, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x02, 0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x54, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6c, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x11, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6f, 0x76, 0x5f, 0x78,
	0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x58, 0x78, 0x12, 0x15,
	0x0a, 0x06, 0x63, 0x6f, 0x76, 0x5f, 0x78, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x63, 0x6f, 0x76, 0x58, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6f, 0x76, 0x5f, 0x79, 0x79, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x59, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tracelet_location_proto_rawDescOnce sync.Once
	file_tracelet_location_proto_rawDescData = file_tracelet_location_proto_rawDesc
)

func file_tracelet_location_proto_rawDescGZIP() []byte {
	file_tracelet_location_proto_rawDescOnce.Do(func() {
		file_tracelet_location_proto_rawDescData = protoimpl.X.CompressGZIP(file_tracelet_location_proto_rawDescData)
	})
	return file_tracelet_location_proto_rawDescData
}

var file_tracelet_location_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tracelet_location_proto_goTypes = []interface{}{
	(*LocationReport)(nil),        // 0: easylocate.LocationReport
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_tracelet_location_proto_depIdxs = []int32{
	1, // 0: easylocate.LocationReport.receive_ts:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tracelet_location_proto_init() }
func file_tracelet_location_proto_init() {
	if File_tracelet_location_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tracelet_location_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tracelet_location_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracelet_location_proto_goTypes,
		DependencyIndexes: file_tracelet_location_proto_depIdxs,
		MessageInfos:      file_tracelet_location_proto_msgTypes,
	}.Build()
	File_tracelet_location_proto = out.File
	file_tracelet_location_proto_rawDesc = nil
	file_tracelet_location_proto_goTypes = nil
	file_tracelet_location_proto_depIdxs = nil
}
