// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: tracelet_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusRequest is sent from the monitoring system (consumer) to Tracelet via
// TCP port
type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id of the request, will be echoed in StatusResponse
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracelet_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracelet_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_tracelet_status_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// StatusResponse is sent from Tracelet to the monitoring system (consumer) via
// TCP port in response to StatusRequest
type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id from StatusRequest
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// number of tracelet power Ups
	PowerUpCount int32 `protobuf:"varint,2,opt,name=power_up_count,json=powerUpCount,proto3" json:"power_up_count,omitempty"`
	// Tracelet has a valid position within easylocate system
	HasPosition bool `protobuf:"varint,3,opt,name=has_position,json=hasPosition,proto3" json:"has_position,omitempty"`
	// Tracelet has connection to location server
	HasServerConnection bool `protobuf:"varint,4,opt,name=has_server_connection,json=hasServerConnection,proto3" json:"has_server_connection,omitempty"`
	// Tracelet has a valid time
	HasTime bool `protobuf:"varint,5,opt,name=has_time,json=hasTime,proto3" json:"has_time,omitempty"`
	// Easylocate module up and running
	ElocModuleStatusOk bool `protobuf:"varint,6,opt,name=eloc_module_status_ok,json=elocModuleStatusOk,proto3" json:"eloc_module_status_ok,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracelet_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracelet_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_tracelet_status_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusResponse) GetPowerUpCount() int32 {
	if x != nil {
		return x.PowerUpCount
	}
	return 0
}

func (x *StatusResponse) GetHasPosition() bool {
	if x != nil {
		return x.HasPosition
	}
	return false
}

func (x *StatusResponse) GetHasServerConnection() bool {
	if x != nil {
		return x.HasServerConnection
	}
	return false
}

func (x *StatusResponse) GetHasTime() bool {
	if x != nil {
		return x.HasTime
	}
	return false
}

func (x *StatusResponse) GetElocModuleStatusOk() bool {
	if x != nil {
		return x.ElocModuleStatusOk
	}
	return false
}

var File_tracelet_status_proto protoreflect.FileDescriptor

var file_tracelet_status_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x72, 0x61, 0x63, 0x65, 0x6c, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x61, 0x73, 0x79, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xeb, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x5f, 0x75, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x68, 0x61, 0x73, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x32, 0x0a, 0x15, 0x68, 0x61, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x13, 0x68, 0x61, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x31, 0x0a, 0x15, 0x65, 0x6c, 0x6f, 0x63, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12,
	0x65, 0x6c, 0x6f, 0x63, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tracelet_status_proto_rawDescOnce sync.Once
	file_tracelet_status_proto_rawDescData = file_tracelet_status_proto_rawDesc
)

func file_tracelet_status_proto_rawDescGZIP() []byte {
	file_tracelet_status_proto_rawDescOnce.Do(func() {
		file_tracelet_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_tracelet_status_proto_rawDescData)
	})
	return file_tracelet_status_proto_rawDescData
}

var file_tracelet_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tracelet_status_proto_goTypes = []interface{}{
	(*StatusRequest)(nil),  // 0: easylocate.StatusRequest
	(*StatusResponse)(nil), // 1: easylocate.StatusResponse
}
var file_tracelet_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracelet_status_proto_init() }
func file_tracelet_status_proto_init() {
	if File_tracelet_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tracelet_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracelet_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tracelet_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracelet_status_proto_goTypes,
		DependencyIndexes: file_tracelet_status_proto_depIdxs,
		MessageInfos:      file_tracelet_status_proto_msgTypes,
	}.Build()
	File_tracelet_status_proto = out.File
	file_tracelet_status_proto_rawDesc = nil
	file_tracelet_status_proto_goTypes = nil
	file_tracelet_status_proto_depIdxs = nil
}
